### ISSUE TITLE
ATT_GT function dropping never treated and always treated groups

### ISSUE THREAD

**Issue by rachelperera** [bcallaway11/did#56]
Hi there,
I'm a relatively novice R user, and so I apologize in advance if I'm missing something obvious.
I'm trying to use your DID program with a panel dataset spanning 10 years (2008 to 2017) that is unique by school-district observation. There is a staggered adoption treatment, with some never treated districts included in the panel as well. Right now, it looks like the att_gt function is automatically dropping the never treated and always treated units. I've reproduced my code and the error message below. The 2026 units that are dropped = 1992 never treated units + 34 always treated units. The att_gt function will provide the ATT estimates for each g,t; but I'd like to include the never treated units in the analysis. I'm not sure why the program is dropping the never treated units. Any advice, or suggestions would be greatly appreciated.

#> remove (list = objects())
#> options(stringsAsFactors = FALSE, width= 80)
#> 
#> # devtools::install_github("bcallaway11/did")
#> library(did)
#> library(readstata13)
#> packageVersion("did")
#[1] ‘2.0.1.906’
#> 
#> setwd("/Users/rperera/Dropbox/OCR Study/")
#> # sink(file="output/log/did_crdc_estimates.txt") 
#> 
#> ######################################################################
#> 
#> ## read in data
#> seda <- read.dta13("generated_data/rq3_seda_analysis_forR.dta")
#> table(seda$year, seda$first_treat)
#>    
#>            0 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
#> 2008 1992   34   24   19   17   14    9   17   14   14   13
#> 2009 1992   34   24   19   17   14    9   17   14   14   13
#> 2010 1992   34   24   19   17   14    9   17   14   14   13
#> 2011 1992   34   24   19   17   14    9   17   14   14   13
#> 2012 1992   34   24   19   17   14    9   17   14   14   13
#> 2013 1992   34   24   19   17   14    9   17   14   14   13
#> 2014 1992   34   24   19   17   14    9   17   14   14   13
#> 2015 1992   34   24   19   17   14    9   17   14   14   13
#> 2016 1992   34   24   19   17   14    9   17   14   14   13
#> 2017 1992   34   24   19   17   14    9   17   14   14   13
#> 

#> ## estimate ATT for each g,t
#> seda.attgt <- att_gt(yname = "whtblk_gap_ela_seda",
#+                      tname = "year", # time variable
#+                      idname = "ncesid", # id variable  
#+                      gname = "first_treat", # first treatment period 
#+                      data = seda,
#+                      # xformla = ~ln_enroll +perc_bl +perc_hi +perc_asp +perc_oth,
#+                      control_group = "notyettreated", 
#+                      clustervars = "ncesid",
#+                      panel = TRUE
#+                     )

#> Warning message:
#> In pre_process_did(yname = yname, tname = tname, idname = idname,  :
#>  Dropped 2026 units that were already treated in the first period.
#> summary(seda.attgt)

#> Call:
#> att_gt(yname = "whtblk_gap_ela_seda", tname = "year", idname = "ncesid", 
#>    gname = "first_treat", data = seda, panel = TRUE, control_group = "notyettreated", 
#>    clustervars = "ncesid")
#> Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time 
#> Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 
#> Group-Time Average Treatment Effects:
#> Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]  
#> 2009 2009   0.0051     0.0245       -0.0636      0.0737  
#>  2009 2010  -0.0002     0.0223       -0.0629      0.0625  
#>  2009 2011   0.0220     0.0590       -0.1435      0.1876  
#> 2009 2012   0.0195     0.0563       -0.1384      0.1774  
#>  2009 2013  -0.0166     0.0779       -0.2353      0.2022  
#> 2009 2014   0.0417     0.0359       -0.0591      0.1424  
#> 2009 2015   0.0230     0.0778       -0.1953      0.2413  
#> 2009 2016   0.0728     0.0355       -0.0270      0.1725  
#> 2009 2017   0.1080     0.0371        0.0038      0.2122 *
#> 2010 2009   0.0416     0.0333       -0.0520      0.1352  
#> 2010 2010  -0.0494     0.0292       -0.1314      0.0325  
#> 2010 2011   0.0380     0.0399       -0.0739      0.1499  
#> 2010 2012  -0.0268     0.0787       -0.2478      0.1942  
#> 2010 2013   0.0462     0.0702       -0.1508      0.2433  
#> 2010 2014   0.0347     0.0560       -0.1224      0.1919  
#> 2010 2015   0.0086     0.0765       -0.2061      0.2233  
#> 2010 2016  -0.0055     0.0667       -0.1928      0.1818  
#> 2010 2017   0.0230     0.0510       -0.1203      0.1663  
#> 2011 2009  -0.0160     0.0372       -0.1204      0.0883  
#> 2011 2010  -0.0788     0.0717       -0.2800      0.1225  
#> 2011 2011   0.0435     0.0263       -0.0304      0.1175  
#> 2011 2012   0.1093     0.0240        0.0418      0.1767 *
#> 2011 2013   0.0982     0.0306        0.0123      0.1842 *
#> 2011 2014   0.1190     0.0302        0.0343      0.2037 *
#> 2011 2015   0.1394     0.0375        0.0342      0.2445 *
#> 2011 2016   0.1178     0.0405        0.0041      0.2315 *
#> 2011 2017   0.1560     0.0326        0.0646      0.2475 *
#> 2012 2009   0.0044     0.0603       -0.1647      0.1735  
#> 2012 2010  -0.0357     0.0296       -0.1189      0.0474  
#> 2012 2011   0.0645     0.1187       -0.2686      0.3976  
#> 2012 2012  -0.0071     0.0818       -0.2367      0.2225  
#> 2012 2013   0.0079     0.0663       -0.1781      0.1938  
#> 2012 2014   0.0289     0.0502       -0.1121      0.1698  
#> 2012 2015   0.0905     0.0750       -0.1200      0.3009  
#> 2012 2016   0.0620     0.0759       -0.1511      0.2751  
#> 2012 2017   0.0181     0.0590       -0.1476      0.1838  
#> 2013 2009   0.0505     0.0486       -0.0857      0.1868  
#> 2013 2010   0.0555     0.0410       -0.0596      0.1707  
#> 2013 2011   0.0289     0.0669       -0.1588      0.2166  
#> 2013 2012   0.1178     0.0434       -0.0041      0.2397  
#> 2013 2013  -0.0587     0.1089       -0.3642      0.2469  
#> 2013 2014  -0.0292     0.1369       -0.4134      0.3550  
#> 2013 2015  -0.0413     0.1241       -0.3896      0.3070  
#> 2013 2016  -0.0646     0.1595       -0.5123      0.3831  
#> 2013 2017  -0.0836     0.1684       -0.5563      0.3890  
#> 2014 2009  -0.0035     0.0287       -0.0840      0.0770  
#> 2014 2010  -0.0494     0.0184       -0.1011      0.0024  
#> 2014 2011  -0.0038     0.0388       -0.1127      0.1050  
#> 2014 2012   0.1278     0.0625       -0.0475      0.3032  
#> 2014 2013  -0.0467     0.0383       -0.1541      0.0607  
#> 2014 2014   0.0053     0.0187       -0.0473      0.0579  
#> 2014 2015  -0.0432     0.0366       -0.1460      0.0596  
#> 2014 2016  -0.0278     0.0236       -0.0939      0.0384  
#> 2014 2017   0.0021     0.0211       -0.0571      0.0612  
#> 2015 2009  -0.0160     0.0277       -0.0937      0.0617  
#> 2015 2010  -0.0138     0.0129       -0.0499      0.0223  
#> 2015 2011  -0.0063     0.0287       -0.0869      0.0744  
#> 2015 2012   0.0649     0.0246       -0.0040      0.1338  
#> 2015 2013   0.0181     0.0255       -0.0533      0.0896  
#> 2015 2014   0.0517     0.0331       -0.0412      0.1446  
#> 2015 2015   0.0204     0.0181       -0.0304      0.0712  
#> 2015 2016   0.0405     0.0375       -0.0648      0.1457  
#> 2015 2017   0.0480     0.0325       -0.0432      0.1392  
#> 2016 2009  -0.0484     0.0227       -0.1121      0.0154  
#> 2016 2010   0.0566     0.0246       -0.0124      0.1255  
#> 2016 2011   0.0024     0.0392       -0.1076      0.1125  
#> 2016 2012   0.0437     0.0351       -0.0547      0.1422  
#> 2016 2013  -0.0077     0.0246       -0.0766      0.0613  
#> 2016 2014  -0.0098     0.0214       -0.0699      0.0504  
#> 2016 2015   0.0118     0.0302       -0.0731      0.0966  
#> 2016 2016   0.0225     0.0267       -0.0524      0.0974  
#> 2016 2017  -0.0011     0.0361       -0.1023      0.1001  
#> 2017 2009  -0.0054     0.0194       -0.0598      0.0490  
#> 2017 2010  -0.0169     0.0187       -0.0694      0.0355  
#> 2017 2011   0.0841     0.0588       -0.0810      0.2492  
#> 2017 2012   0.0105     0.0846       -0.2270      0.2479  
#> 2017 2013   0.0056     0.0459       -0.1232      0.1344  
#> 2017 2014  -0.0312     0.0561       -0.1888      0.1264  
#> 2017 2015   0.0096     0.0178       -0.0404      0.0597  
#> 2017 2016  -0.0161     0.0337       -0.1106      0.0785  
#> 2017 2017  -0.0021     0.0191       -0.0559      0.0516  
#> ---
#> Signif. codes: `*' confidence band does not cover 0
#>
#> P-value for pre-test of parallel trends assumption:  0
#> Control Group:  Not Yet Treated,  Anticipation Periods:  0
#> Estimation Method:  Doubly Robust
#>

**Comment by bcallaway11** [comment]
Hi Rachel,

I believe that the code that is currently on CRAN has a bug in it so that it reports that it drops never treated units (it doesn't actually drop these, it just says that it does).  If it were dropping these, it wouldn't be able to compute an ATT(g,t) in the last period --- this is why this is my guess at what is going on.

So I think you can ignore this.  Alternatively, if you would feel better about it, you can delete the version from CRAN, load the github code (use: `devtools::install_github("bcallaway11/did")`) where this bug is fixed.  The github version is leading CRAN a little, but we'll update CRAN at some point over the summer.

Hope this helps.  I'm also not 100% sure that this will fix your issue, so if not, please feel free to follow up.

Brant

**Comment by rachelperera** [comment]
Hi Brant,
Thank you so much for the quick reply-- now that you point out the estimated ATT for the last period, that makes total sense that the never treated groups have in fact been included in the analysis. That said, as an FYI, I installed the latest version of the DID package from your github and I still get the same error message.  

#> packageVersion("did")
#> [1] ‘2.0.1.906’

I have one additional question-- (and I'm let me know if I should submit a new issue). I am estimating essentially the same model but with an 8 year panel (due to missingness in a different outcome variable of interest). The DID program produces ATT estimates for each g,t; however when I try to aggregate the individual cohort by time estimates to produce an event study graph, the program produces "NA" for the standard errors. Is there any intuition as to why the program won't produce SE/CI around the ES estimates? Any additional help would be greatly appreciated!  Code and results here:
[did_crdc_estimates.txt](https://github.com/bcallaway11/did/files/6381740/did_crdc_estimates.txt)

**Comment by pedrohcgs** [comment]
Rachel, could you send us a sample of your data so we can reproduce these issues? You can send by email if you prefer. Thanks

**Comment by rachelperera** [comment]
Great, thank you! I just followed up via email with my data.

**Comment by bcallaway11** [comment]
Hi Rachel,

I think I got to the bottom of this:

* Easy part: I'm not sure why you were still getting the (incorrect) warning about dropping units, but I updated the version to 2.01.907, and the issue will be fixed there.
* Pedro emailed me the data that you sent him, and I think I have figured out the issue.  Notice that

```
sort(unique(crdc$time))
[1]  1  3  4  6  7  8  9 10

 sort(unique(crdc$first_treat))
 [1]  0  1  2  3  4  5  6  7  8  9 10
```

so there are groups in all time periods, but there are some unavailable time periods (no period 2 or time period 5).  Our code seems to work here just fine for computing ATT(g,t), but the "dynamic" aggregation doesn't work.  This is basically a bug in our code (or at unequally spaced time periods are just more challenging to keep track of when aggregating across groups and time periods).  I'll try to get this figured out and post an update, but, realistically, it might take a while.  In the meantime, probably the best thing to do depends on the particular application that you're working on, but one idea would be to just aggregate time periods into even numbered time periods which would seem to get rid of periods being unequally spaced [sorry that I don't have a better solution...]

**Comment by rachelperera** [comment]
That makes a lot of sense -- I'll think through what to do in the interim. Many thanks for the help and quick replies!!

**Comment by fschoner** [comment]
Related question: In a setting without never-treated units, i.e. with
```r
notyettreated = TRUE
```
why don't always-treated units (they have first_treat <= min(time_variable)) get dropped entirely?

**Comment by bcallaway11** [comment]
I think our code does drop always-treated units in this case (code below, which I think mimics the setup that you are talking about here, drops them and only computes ATT(g,t) for g=2006 in 2005 and 2006 (this is what should happen here).  If I am misunderstanding something, just let me know.

As far as including/excluding always-treated units, we always drop them.  Parallel trends assumptions are usually about untreated potential outcomes, and this means that DID is most useful for identifying treatment effect parameters among units that move from being untreated to treated at some point in time.  Never treated units are potentially useful in the comparison group, but always-treated units aren't used at all (and it doesn't make sense to use them unless you are willing to believer other assumptions related to limiting treatment effect dynamics or something like that).

Brant

```
library(did)
library(tidyverse)

data(mpdta)

sort(unique(mpdta$first.treat))

mpdta <- subset(mpdta, year >= 2004)
mpdta <- subset(mpdta, first.treat != 0)
nrow(mpdta)

out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~1,
              data = mpdta,
              est_method = "reg",
              panel=TRUE,
              allow_unbalanced_panel=TRUE,
              control_group="notyettreated"
              )

summary(out)
```

**Comment by fschoner** [comment]
Dear Brant,

thanks for your quick and helpful response. I figured out what caused my confusion by manually manipulating the sample to mimic the one att_gt actually uses for estimation.

**Comment by bcallaway11** [comment]
I think this specific issue is solved.  I opened a new issue for the general problem of having more groups than time periods: #89
